version: "3"
services:
  db:
    image: postgres:12.9
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432/tcp"
    networks:
      datagrok:
        aliases:
          - database
    volumes:
      - datagrok_db:/var/lib/postgresql/data
    restart: on-failure
    profiles: [ "all", "db" ]

  northwind:
    image: datagrok/demo_db:latest
    environment:
      POSTGRES_DB: northwind
    networks:
      datagrok:
        aliases:
          - northwind
    volumes:
      - datagrok_postgres_northwind:/var/lib/postgresql/data
    restart: on-failure
    profiles: [ "demo", "postgres_northwind", "northwind" ]

  chembl:
    image: datagrok/demo_db_chembl:latest
    environment:
      POSTGRES_DB: chembl
    networks:
      datagrok:
        aliases:
          - chembl
    volumes:
      - datagrok_postgres_chembl:/var/lib/postgresql/data
    restart: on-failure
    profiles: [ "demo", "postgres_chembl", "chembl" ]

  unichem:
    image: datagrok/demo_db_unichem:latest
    environment:
      POSTGRES_DB: unichem
    networks:
      datagrok:
        aliases:
          - unichem
    volumes:
      - datagrok_postgres_unichem:/var/lib/postgresql/data
    restart: on-failure
    profiles: [ "demo", "postgres_unichem", "unichem" ]

  starbucks:
    image: datagrok/demo_db:latest
    environment:
      POSTGRES_DB: starbucks
    networks:
      datagrok:
        aliases:
          - starbucks
    volumes:
      - datagrok_postgres_starbucks:/var/lib/postgresql/data
    restart: on-failure
    profiles: [ "demo", "postgres_starbucks", "starbucks" ]

  world:
    image: datagrok/demo_db:latest
    environment:
      POSTGRES_DB: world
    networks:
      datagrok:
        aliases:
          - world
    volumes:
      - datagrok_postgres_world:/var/lib/postgresql/data
    restart: on-failure
    profiles: [ "demo", "postgres_world", "world" ]

  datagrok:
    image: datagrok/datagrok:latest
    environment:
      GROK_PARAMETERS: "{
        \"deployDemo\": false,
        \"dbServer\": \"database\",
        \"db\": \"datagrok\",
        \"dbAdminLogin\": \"postgres\",
        \"dbAdminPassword\": \"postgres\",
        \"dbLogin\": \"dg\",
        \"dbPassword\": \"dg\",
        \"adminPassword\": \"admin\"
      }"
#      GROK_COMPONENTS: "${COMPOSE_PROFILES:?err}"
    ports:
      - "8080:8080/tcp"
    networks:
      datagrok:
        aliases:
          - datagrok
    volumes:
      - datagrok_data:/home/grok/data
      - datagrok_cfg:/home/grok/cfg
    restart: unless-stopped
    profiles: [ "all", "datagrok" ]

  grok_connect:
    image: datagrok/grok_connect:latest
    networks:
      datagrok:
        aliases:
          - grok_connect
    restart: unless-stopped
    profiles: [ "all", "datagrok", "grok_connect" ]

  grok_compute:
    image: datagrok/grok_compute:latest
    environment:
      GROK_COMPUTE_NUM_CORES: 2
    networks:
      datagrok:
        aliases:
          - grok_compute
    restart: unless-stopped
    profiles: [ "all", "cvm", "chem" ]

  cvm_nginx:
    image: datagrok/cvm_nginx:latest
    ports:
      - "8090:8090/tcp"
    networks:
      datagrok:
        aliases:
          - cvm
          - nginx_cvm
    restart: unless-stopped
    profiles: [ "all", "cvm", "chem", "jupyter_notebook", "scripting" ]

  jupyter_notebook:
    image: datagrok/jupyter_notebook:latest
    networks:
      datagrok:
        aliases:
          - jupyter_notebook
    restart: unless-stopped
    profiles: [ "all", "cvm", "jupyter_notebook" ]

  jupyter_kernel_gateway:
    image: datagrok/jupyter_kernel_gateway:latest
    networks:
      datagrok:
        aliases:
          - jupyter_kernel_gateway
    restart: unless-stopped
    profiles: [ "all", "cvm", "scripting" ]

  h2o:
    image: datagrok/h2o:latest
    ports:
      - "54321:54321/tcp"
      - "5005:5005/tcp"
    networks:
      datagrok:
        aliases:
          - h2o
    restart: unless-stopped
    profiles: [ "all", "cvm", "modeling" ]

volumes:
  datagrok_db:
  datagrok_data:
  datagrok_cfg:
  datagrok_postgres_northwind:
  datagrok_postgres_chembl:
  datagrok_postgres_starbucks:
  datagrok_postgres_world:
  datagrok_postgres_unichem:

networks:
  datagrok:
