name: JS API Package
on:
  workflow_dispatch: { }
  push:
    paths:
      - 'js-api/package.json'
jobs:
  check:
    name: Check version was changed
    runs-on: ubuntu-20.04
    outputs:
      changed_version: ${{ steps.check-version.outputs.changed_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check version was changed
        id: check-version
        working-directory: ./js-api
        run: |
          set -ex
          name="$(jq .name package.json | sed 's/"//g')"
          current_version="$(jq .version package.json | sed 's/"//g')"
            npm_response="$(curl --retry 3 "https://registry.npmjs.org/${name}/${current_version}")"
          if [[ $npm_response == "\"version not found: ${current_version}\"" ]]; then
            changed_version='true'
          else
            changed_version='false'
          fi
          echo "::set-output name=changed_version::${changed_version}"

  build:
    name: Build and publish to npm
    runs-on: ubuntu-20.04
    needs: check
    if: needs.check.outputs.changed_version == 'true'
    environment: Prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Upgrade npm
        run: npm install -g npm@latest
      - name: npm version
        run: npm version
      - run: npm install
        working-directory: ./js-api
      - run: npm run build
        working-directory: ./js-api
      - run: npm run build-ts
        working-directory: ./js-api
      - run: npm publish
        working-directory: ./js-api
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Commit package-lock.json
        run: |
          if [ -n "$(git status -s js-api/package-lock.json)" ]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'githubactions@datagrok.ai'
            git pull
            git add js-api/package-lock.json
            git commit -m "GitHub Actions: Update js-api/package-lock.json"
            count=0
            until git push; do
              exit=$?
              wait=$((2 ** count))
              count=$((count + 1))
              if [ $count -lt "10" ]; then
                echo "Retry $count/$retries exited $exit, retrying 'git push' in $wait seconds..."
                sleep $wait
                git pull --rebase
              else
                echo "Retry $count/$retries exited $exit, no more retries left for 'git push'."
                exit $exit
              fi
            done
          fi
