---
name: Lint Code Base
on:
  workflow_dispatch: { }
  push:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          MULTI_STATUS: true
          LOG_LEVEL: WARN
          ERROR_ON_MISSING_EXEC_BIT: true
          SUPPRESS_FILE_TYPE_WARN: false
          IGNORE_GITIGNORED_FILES: true
          JSCPD_CONFIG_FILE: .jscpd.json
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          NATURAL_LANGUAGE_CONFIG_FILE: .textlintrc
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_CPP: true
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_CLOUDFORMATION: true
          VALIDATE_CSS: true
#          VALIDATE_DART: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_GOOGLE_JAVA_FORMAT: true
          VALIDATE_HTML: true
          VALIDATE_JAVA: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_STANDARD: true
          VALIDATE_JSCPD: true
          VALIDATE_JSON: true
          VALIDATE_JSX: true
#          VALIDATE_KUBERNETES_KUBEVAL: true
          VALIDATE_LUA: true
          VALIDATE_MARKDOWN: true
          VALIDATE_NATURAL_LANGUAGE: true
          VALIDATE_POWERSHELL: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_TERRAFORM_TERRASCAN: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_TSX: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_TYPESCRIPT_STANDARD: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
