name: "Security Scan"

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    branches-ignore:
      - 'dependabot/**'

jobs:
  codeql:
    name: CodeQL static analysis
    runs-on: ubuntu-20.04
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java', 'javascript' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 8
        if: matrix.language == 'java'
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  anchore:
    runs-on: ubuntu-20.04
    name: Anchore vulnerability scan
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan for GitHub Secutiry
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "."
          fail-build: false # Change to true after all fixes
          severity-cutoff: high
          acs-report-enable: true
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
